//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_InstructorUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ST_InstructorUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIT.
        /// </summary>
        internal static string button_Init_Text {
            get {
                return ResourceManager.GetString("button_Init.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string buttonClearGame_Text {
            get {
                return ResourceManager.GetString("buttonClearGame.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string buttonClearPartner_Text {
            get {
                return ResourceManager.GetString("buttonClearPartner.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string buttonClearPlayer_Text {
            get {
                return ResourceManager.GetString("buttonClearPlayer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Tags.
        /// </summary>
        internal static string buttonClearTags_Text {
            get {
                return ResourceManager.GetString("buttonClearTags.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Goal.
        /// </summary>
        internal static string buttonGoal_Text {
            get {
                return ResourceManager.GetString("buttonGoal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ③Go to Main Screen.
        /// </summary>
        internal static string buttonGotoMain_Text {
            get {
                return ResourceManager.GetString("buttonGotoMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string buttonInit_Text {
            get {
                return ResourceManager.GetString("buttonInit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ②Floor Initialization.
        /// </summary>
        internal static string buttonInitFloor_Text {
            get {
                return ResourceManager.GetString("buttonInitFloor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ①System Initialization.
        /// </summary>
        internal static string buttonInitSystem_Text {
            get {
                return ResourceManager.GetString("buttonInitSystem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Run.
        /// </summary>
        internal static string buttonLoad_Text {
            get {
                return ResourceManager.GetString("buttonLoad.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string buttonRandomBackground_Text {
            get {
                return ResourceManager.GetString("buttonRandomBackground.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string buttonRandomColor_Text {
            get {
                return ResourceManager.GetString("buttonRandomColor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message to All Clients.
        /// </summary>
        internal static string buttonSendAll_Text {
            get {
                return ResourceManager.GetString("buttonSendAll.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string buttonStart_Text {
            get {
                return ResourceManager.GetString("buttonStart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string buttonStop_Text {
            get {
                return ResourceManager.GetString("buttonStop.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A client or UI application is already running.
        /// </summary>
        internal static string Dialog_ClientAlreadyRunning {
            get {
                return ResourceManager.GetString("Dialog.ClientAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Abort.
        /// </summary>
        internal static string Dialog_ConfirmAbort {
            get {
                return ResourceManager.GetString("Dialog.ConfirmAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you abort during replay or silent period, data will not be saved. Do you really want to abort?
        ///
        ///(OK = Abort, Cancel = Continue).
        /// </summary>
        internal static string Dialog_ConfirmAbortMessage {
            get {
                return ResourceManager.GetString("Dialog.ConfirmAbortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Dialog_Confirmation {
            get {
                return ResourceManager.GetString("Dialog.Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The run will not be recorded. Are you sure?.
        /// </summary>
        internal static string Dialog_ConfirmNoRecord {
            get {
                return ResourceManager.GetString("Dialog.ConfirmNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports Time Machine UI.
        /// </summary>
        internal static string Form1_Text {
            get {
                return ResourceManager.GetString("Form1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal.
        /// </summary>
        internal static string Label_AnimalPartner {
            get {
                return ResourceManager.GetString("Label.AnimalPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Label_PlayerFormat {
            get {
                return ResourceManager.GetString("Label.PlayerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player QR.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record QR.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner QR.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR from Camera.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Color.
        /// </summary>
        internal static string label6_Text {
            get {
                return ResourceManager.GetString("label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Tags (will be reflected in the bottom row).
        /// </summary>
        internal static string label7_Text {
            get {
                return ResourceManager.GetString("label7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Stop Commands.
        /// </summary>
        internal static string label8_Text {
            get {
                return ResourceManager.GetString("label8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on the connection status, the &quot;System Initialization&quot; may already be completed
        ///when the instructor software starts, and the &quot;Floor Initialization&quot; button may be enabled..
        /// </summary>
        internal static string label9_Text {
            get {
                return ResourceManager.GetString("label9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name will be displayed here.
        /// </summary>
        internal static string labelPartnerName_Text {
            get {
                return ResourceManager.GetString("labelPartnerName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name will be displayed here.
        /// </summary>
        internal static string labelPlayerName_Text {
            get {
                return ResourceManager.GetString("labelPlayerName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string languageToggleButton_Text {
            get {
                return ResourceManager.GetString("languageToggleButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #NODATA#.
        /// </summary>
        internal static string NoQRData {
            get {
                return ResourceManager.GetString("NoQRData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrating floor.
        /// </summary>
        internal static string StatusMessage_Calibrating {
            get {
                return ResourceManager.GetString("StatusMessage.Calibrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTED: .
        /// </summary>
        internal static string StatusMessage_Connected {
            get {
                return ResourceManager.GetString("StatusMessage.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string StatusMessage_Error {
            get {
                return ResourceManager.GetString("StatusMessage.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        internal static string StatusMessage_Initializing {
            get {
                return ResourceManager.GetString("StatusMessage.Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Game QR code.
        /// </summary>
        internal static string StatusMessage_InvalidGameQR {
            get {
                return ResourceManager.GetString("StatusMessage.InvalidGameQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Player QR code.
        /// </summary>
        internal static string StatusMessage_InvalidPlayerQR {
            get {
                return ResourceManager.GetString("StatusMessage.InvalidPlayerQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data.
        /// </summary>
        internal static string StatusMessage_Loading {
            get {
                return ResourceManager.GetString("StatusMessage.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Sports Time Machine QR code.
        /// </summary>
        internal static string StatusMessage_NonSTQR {
            get {
                return ResourceManager.GetString("StatusMessage.NonSTQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StatusMessage_OK {
            get {
                return ResourceManager.GetString("StatusMessage.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing back.
        /// </summary>
        internal static string StatusMessage_PlayingBack {
            get {
                return ResourceManager.GetString("StatusMessage.PlayingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read QR file.
        /// </summary>
        internal static string StatusMessage_QRFileError {
            get {
                return ResourceManager.GetString("StatusMessage.QRFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to run.
        /// </summary>
        internal static string StatusMessage_Ready {
            get {
                return ResourceManager.GetString("StatusMessage.Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        internal static string StatusMessage_Running {
            get {
                return ResourceManager.GetString("StatusMessage.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string StatusMessage_Saving {
            get {
                return ResourceManager.GetString("StatusMessage.Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered Player QR code.
        /// </summary>
        internal static string StatusMessage_UnregisteredPlayerQR {
            get {
                return ResourceManager.GetString("StatusMessage.UnregisteredPlayerQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording complete.
        /// </summary>
        internal static string StatusMessage_WaitingPlayback {
            get {
                return ResourceManager.GetString("StatusMessage.WaitingPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for start.
        /// </summary>
        internal static string StatusMessage_WaitingRun {
            get {
                return ResourceManager.GetString("StatusMessage.WaitingRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Screen.
        /// </summary>
        internal static string tabPage_Admin_Text {
            get {
                return ResourceManager.GetString("tabPage_Admin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Screen.
        /// </summary>
        internal static string tabPage_Main_Text {
            get {
                return ResourceManager.GetString("tabPage_Main.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization Screen.
        /// </summary>
        internal static string tabPage_System_Text {
            get {
                return ResourceManager.GetString("tabPage_System.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After starting up 6 clients and the server, press the &quot;System Initialization&quot; button.
        ///After initialization, the standby (idle) music and announcement voice will start playing from the beginning.
        ///    .
        /// </summary>
        internal static string textBox1_Text {
            get {
                return ResourceManager.GetString("textBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform &quot;Floor Initialization&quot; about 3 minutes after &quot;System Initialization&quot;.
        ///At this time, make sure that no one is in the running area (in front of the screen).
        ///The screen will turn black during floor initialization.
        ///    .
        /// </summary>
        internal static string textBox2_Text {
            get {
                return ResourceManager.GetString("textBox2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the two initializations are complete,
        ///go to the main screen with this button..
        /// </summary>
        internal static string textBox3_Text {
            get {
                return ResourceManager.GetString("textBox3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string toolStripStatusLabel1_Text {
            get {
                return ResourceManager.GetString("toolStripStatusLabel1.Text", resourceCulture);
            }
        }
    }
}
