//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_InstructorUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ko_KR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ko_KR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ST_InstructorUI.Properties.Resources.ko-KR", typeof(Resources_ko_KR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIT.
        /// </summary>
        internal static string button_Init_Text {
            get {
                return ResourceManager.GetString("button_Init.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 클리어.
        /// </summary>
        internal static string buttonClearGame_Text {
            get {
                return ResourceManager.GetString("buttonClearGame.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 클리어.
        /// </summary>
        internal static string buttonClearPartner_Text {
            get {
                return ResourceManager.GetString("buttonClearPartner.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 클리어.
        /// </summary>
        internal static string buttonClearPlayer_Text {
            get {
                return ResourceManager.GetString("buttonClearPlayer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전체 태그 선택 해제.
        /// </summary>
        internal static string buttonClearTags_Text {
            get {
                return ResourceManager.GetString("buttonClearTags.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 수동 골 설정.
        /// </summary>
        internal static string buttonGoal_Text {
            get {
                return ResourceManager.GetString("buttonGoal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ③메인화면으로.
        /// </summary>
        internal static string buttonGotoMain_Text {
            get {
                return ResourceManager.GetString("buttonGotoMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 중단.
        /// </summary>
        internal static string buttonInit_Text {
            get {
                return ResourceManager.GetString("buttonInit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ②바닥 정보 초기화.
        /// </summary>
        internal static string buttonInitFloor_Text {
            get {
                return ResourceManager.GetString("buttonInitFloor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ①시스템 초기화.
        /// </summary>
        internal static string buttonInitSystem_Text {
            get {
                return ResourceManager.GetString("buttonInitSystem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 경기 참가 준비.
        /// </summary>
        internal static string buttonLoad_Text {
            get {
                return ResourceManager.GetString("buttonLoad.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 랜덤.
        /// </summary>
        internal static string buttonRandomBackground_Text {
            get {
                return ResourceManager.GetString("buttonRandomBackground.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 랜덤.
        /// </summary>
        internal static string buttonRandomColor_Text {
            get {
                return ResourceManager.GetString("buttonRandomColor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모든 클라이언트에 메시지 전송.
        /// </summary>
        internal static string buttonSendAll_Text {
            get {
                return ResourceManager.GetString("buttonSendAll.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시작.
        /// </summary>
        internal static string buttonStart_Text {
            get {
                return ResourceManager.GetString("buttonStart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다시 시도.
        /// </summary>
        internal static string buttonStop_Text {
            get {
                return ResourceManager.GetString("buttonStop.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 클라이언트 또는 UI 애플리케이션이 이미 실행 중입니다.
        /// </summary>
        internal static string Dialog_ClientAlreadyRunning {
            get {
                return ResourceManager.GetString("Dialog.ClientAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 중단 확인.
        /// </summary>
        internal static string Dialog_ConfirmAbort {
            get {
                return ResourceManager.GetString("Dialog.ConfirmAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리플레이나 무음 시간 중에 중단하면 데이터가 저장되지 않습니다. 정말로 중단하시겠습니까?
        ///
        ///(확인 = 중단, 취소 = 계속).
        /// </summary>
        internal static string Dialog_ConfirmAbortMessage {
            get {
                return ResourceManager.GetString("Dialog.ConfirmAbortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인.
        /// </summary>
        internal static string Dialog_Confirmation {
            get {
                return ResourceManager.GetString("Dialog.Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 달리기 데이터가 기록되지 않습니다. 계속하시겠습니까?.
        /// </summary>
        internal static string Dialog_ConfirmNoRecord {
            get {
                return ResourceManager.GetString("Dialog.ConfirmNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스포츠 타임머신 UI.
        /// </summary>
        internal static string Form1_Text {
            get {
                return ResourceManager.GetString("Form1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 동물.
        /// </summary>
        internal static string Label_AnimalPartner {
            get {
                return ResourceManager.GetString("Label.AnimalPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 님.
        /// </summary>
        internal static string Label_PlayerFormat {
            get {
                return ResourceManager.GetString("Label.PlayerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 플레이어 QR.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기록할 QR.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파트너 QR.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카메라에서의 QR.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배경.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 플레이어의 색.
        /// </summary>
        internal static string label6_Text {
            get {
                return ResourceManager.GetString("label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 추가 태그.
        /// </summary>
        internal static string label7_Text {
            get {
                return ResourceManager.GetString("label7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시작이나 경기 참가의 명령.
        /// </summary>
        internal static string label8_Text {
            get {
                return ResourceManager.GetString("label8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 접속 상태에 따라서는 인스트럭터용 소프트의 기동 시, 이미 「시스템 초기화」가 끝나 있어 
        ///「바닥 정보 초기화」버튼이 활성화 되어 있는 경우도 있습니다..
        /// </summary>
        internal static string label9_Text {
            get {
                return ResourceManager.GetString("label9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 여기에 이름이 표시됩니다..
        /// </summary>
        internal static string labelPartnerName_Text {
            get {
                return ResourceManager.GetString("labelPartnerName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 여기에 이름이 표시됩니다..
        /// </summary>
        internal static string labelPlayerName_Text {
            get {
                return ResourceManager.GetString("labelPlayerName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한국어.
        /// </summary>
        internal static string languageToggleButton_Text {
            get {
                return ResourceManager.GetString("languageToggleButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #NODATA#.
        /// </summary>
        internal static string NoQRData {
            get {
                return ResourceManager.GetString("NoQRData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 바닥 보정 중.
        /// </summary>
        internal static string StatusMessage_Calibrating {
            get {
                return ResourceManager.GetString("StatusMessage.Calibrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연결됨:.
        /// </summary>
        internal static string StatusMessage_Connected {
            get {
                return ResourceManager.GetString("StatusMessage.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오류.
        /// </summary>
        internal static string StatusMessage_Error {
            get {
                return ResourceManager.GetString("StatusMessage.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 초기화 중.
        /// </summary>
        internal static string StatusMessage_Initializing {
            get {
                return ResourceManager.GetString("StatusMessage.Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유효하지 않은 게임 QR 코드.
        /// </summary>
        internal static string StatusMessage_InvalidGameQR {
            get {
                return ResourceManager.GetString("StatusMessage.InvalidGameQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유효하지 않은 플레이어 QR 코드.
        /// </summary>
        internal static string StatusMessage_InvalidPlayerQR {
            get {
                return ResourceManager.GetString("StatusMessage.InvalidPlayerQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터 로딩 중.
        /// </summary>
        internal static string StatusMessage_Loading {
            get {
                return ResourceManager.GetString("StatusMessage.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스포츠 타임머신 QR 코드가 아님.
        /// </summary>
        internal static string StatusMessage_NonSTQR {
            get {
                return ResourceManager.GetString("StatusMessage.NonSTQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StatusMessage_OK {
            get {
                return ResourceManager.GetString("StatusMessage.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 재생 중.
        /// </summary>
        internal static string StatusMessage_PlayingBack {
            get {
                return ResourceManager.GetString("StatusMessage.PlayingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR 파일을 읽을 수 없음.
        /// </summary>
        internal static string StatusMessage_QRFileError {
            get {
                return ResourceManager.GetString("StatusMessage.QRFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 달리기 준비 완료.
        /// </summary>
        internal static string StatusMessage_Ready {
            get {
                return ResourceManager.GetString("StatusMessage.Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기록 중.
        /// </summary>
        internal static string StatusMessage_Running {
            get {
                return ResourceManager.GetString("StatusMessage.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 저장 중.
        /// </summary>
        internal static string StatusMessage_Saving {
            get {
                return ResourceManager.GetString("StatusMessage.Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록되지 않은 플레이어 QR 코드.
        /// </summary>
        internal static string StatusMessage_UnregisteredPlayerQR {
            get {
                return ResourceManager.GetString("StatusMessage.UnregisteredPlayerQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기록 완료.
        /// </summary>
        internal static string StatusMessage_WaitingPlayback {
            get {
                return ResourceManager.GetString("StatusMessage.WaitingPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시작 대기 중.
        /// </summary>
        internal static string StatusMessage_WaitingRun {
            get {
                return ResourceManager.GetString("StatusMessage.WaitingRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 관리자화면.
        /// </summary>
        internal static string tabPage_Admin_Text {
            get {
                return ResourceManager.GetString("tabPage_Admin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메인화면.
        /// </summary>
        internal static string tabPage_Main_Text {
            get {
                return ResourceManager.GetString("tabPage_Main.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 초기화화면.
        /// </summary>
        internal static string tabPage_System_Text {
            get {
                return ResourceManager.GetString("tabPage_System.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6대의 클라이언트와 서버를 기동하고 나면, 「시스템 초기화」버튼을 눌러주세요. 
        ///초기화하면 대기 시간(idle 시간)의 음악과 안내의 소리가 나오기 시작합니다..
        /// </summary>
        internal static string textBox1_Text {
            get {
                return ResourceManager.GetString("textBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「시스템 초기화」후, 3분 정도 지나고 나서 「바닥 정보 초기화」를 실시합니다. 
        ///이때, 달리는 장소(스크린의 앞)에 아무도 없는 것을 확인해 주세요. 
        ///바닥 정보를 초기화하고 있는 동안은, 화면이 검게 어두워집니다.
        ///.
        /// </summary>
        internal static string textBox2_Text {
            get {
                return ResourceManager.GetString("textBox2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 두 개의 초기화가 끝나면
        ///이 버튼을 통해서 메인화면으로 넘어가도록 하겠습니다..
        /// </summary>
        internal static string textBox3_Text {
            get {
                return ResourceManager.GetString("textBox3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string toolStripStatusLabel1_Text {
            get {
                return ResourceManager.GetString("toolStripStatusLabel1.Text", resourceCulture);
            }
        }
    }
}
