//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_InstructorUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ja_JP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ST_InstructorUI.Properties.Resources.ja-JP", typeof(Resources_ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIT.
        /// </summary>
        internal static string button_Init_Text {
            get {
                return ResourceManager.GetString("button_Init.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリア.
        /// </summary>
        internal static string buttonClearGame_Text {
            get {
                return ResourceManager.GetString("buttonClearGame.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリア.
        /// </summary>
        internal static string buttonClearPartner_Text {
            get {
                return ResourceManager.GetString("buttonClearPartner.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリア.
        /// </summary>
        internal static string buttonClearPlayer_Text {
            get {
                return ResourceManager.GetString("buttonClearPlayer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全タグの選択解除.
        /// </summary>
        internal static string buttonClearTags_Text {
            get {
                return ResourceManager.GetString("buttonClearTags.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手動でゴール.
        /// </summary>
        internal static string buttonGoal_Text {
            get {
                return ResourceManager.GetString("buttonGoal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ③メイン画面へ.
        /// </summary>
        internal static string buttonGotoMain_Text {
            get {
                return ResourceManager.GetString("buttonGotoMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中断.
        /// </summary>
        internal static string buttonInit_Text {
            get {
                return ResourceManager.GetString("buttonInit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ②床情報の初期化.
        /// </summary>
        internal static string buttonInitFloor_Text {
            get {
                return ResourceManager.GetString("buttonInitFloor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ①システムの初期化.
        /// </summary>
        internal static string buttonInitSystem_Text {
            get {
                return ResourceManager.GetString("buttonInitSystem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出走の準備.
        /// </summary>
        internal static string buttonLoad_Text {
            get {
                return ResourceManager.GetString("buttonLoad.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランダム.
        /// </summary>
        internal static string buttonRandomBackground_Text {
            get {
                return ResourceManager.GetString("buttonRandomBackground.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランダム.
        /// </summary>
        internal static string buttonRandomColor_Text {
            get {
                return ResourceManager.GetString("buttonRandomColor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全クライアントにメッセージ.
        /// </summary>
        internal static string buttonSendAll_Text {
            get {
                return ResourceManager.GetString("buttonSendAll.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタート.
        /// </summary>
        internal static string buttonStart_Text {
            get {
                return ResourceManager.GetString("buttonStart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to やりなおし.
        /// </summary>
        internal static string buttonStop_Text {
            get {
                return ResourceManager.GetString("buttonStop.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すでにクライアントもしくはUIアプリが起動しています.
        /// </summary>
        internal static string Dialog_ClientAlreadyRunning {
            get {
                return ResourceManager.GetString("Dialog.ClientAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認です.
        /// </summary>
        internal static string Dialog_Confirmation {
            get {
                return ResourceManager.GetString("Dialog.Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 走ったデータは記録されません。よいですか？.
        /// </summary>
        internal static string Dialog_ConfirmNoRecord {
            get {
                return ResourceManager.GetString("Dialog.ConfirmNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スポーツタイムマシン UI.
        /// </summary>
        internal static string Form1_Text {
            get {
                return ResourceManager.GetString("Form1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to どうぶつ.
        /// </summary>
        internal static string Label_AnimalPartner {
            get {
                return ResourceManager.GetString("Label.AnimalPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} さん.
        /// </summary>
        internal static string Label_PlayerFormat {
            get {
                return ResourceManager.GetString("Label.PlayerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイヤーQR.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 記録するQR.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パートナーQR.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カメラからのQR.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイヤーの色.
        /// </summary>
        internal static string label6_Text {
            get {
                return ResourceManager.GetString("label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加のタグ（最下段に反映されます）.
        /// </summary>
        internal static string label7_Text {
            get {
                return ResourceManager.GetString("label7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始や終了の命令.
        /// </summary>
        internal static string label8_Text {
            get {
                return ResourceManager.GetString("label8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続状態によっては、インストラクター用ソフトの起動時、すでに「システムの初期化」がおわっており、
        ///「床情報の初期化」ボタンが有効になっていることもあります。.
        /// </summary>
        internal static string label9_Text {
            get {
                return ResourceManager.GetString("label9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ここに名前が表示されます.
        /// </summary>
        internal static string labelPartnerName_Text {
            get {
                return ResourceManager.GetString("labelPartnerName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ここに名前が表示されます.
        /// </summary>
        internal static string labelPlayerName_Text {
            get {
                return ResourceManager.GetString("labelPlayerName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string languageToggleButton_Text {
            get {
                return ResourceManager.GetString("languageToggleButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #NODATA#.
        /// </summary>
        internal static string NoQRData {
            get {
                return ResourceManager.GetString("NoQRData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 床の初期化中.
        /// </summary>
        internal static string StatusMessage_Calibrating {
            get {
                return ResourceManager.GetString("StatusMessage.Calibrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続しました: .
        /// </summary>
        internal static string StatusMessage_Connected {
            get {
                return ResourceManager.GetString("StatusMessage.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 動作不良.
        /// </summary>
        internal static string StatusMessage_Error {
            get {
                return ResourceManager.GetString("StatusMessage.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初期化中.
        /// </summary>
        internal static string StatusMessage_Initializing {
            get {
                return ResourceManager.GetString("StatusMessage.Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ただしくないゲームQRコードです.
        /// </summary>
        internal static string StatusMessage_InvalidGameQR {
            get {
                return ResourceManager.GetString("StatusMessage.InvalidGameQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在しないプレイヤーQRコードです.
        /// </summary>
        internal static string StatusMessage_InvalidPlayerQR {
            get {
                return ResourceManager.GetString("StatusMessage.InvalidPlayerQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データロード中.
        /// </summary>
        internal static string StatusMessage_Loading {
            get {
                return ResourceManager.GetString("StatusMessage.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スポーツタイムマシン以外のQRコードです.
        /// </summary>
        internal static string StatusMessage_NonSTQR {
            get {
                return ResourceManager.GetString("StatusMessage.NonSTQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StatusMessage_OK {
            get {
                return ResourceManager.GetString("StatusMessage.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイバック中.
        /// </summary>
        internal static string StatusMessage_PlayingBack {
            get {
                return ResourceManager.GetString("StatusMessage.PlayingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRファイルが読めません.
        /// </summary>
        internal static string StatusMessage_QRFileError {
            get {
                return ResourceManager.GetString("StatusMessage.QRFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出走可能.
        /// </summary>
        internal static string StatusMessage_Ready {
            get {
                return ResourceManager.GetString("StatusMessage.Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 記録中.
        /// </summary>
        internal static string StatusMessage_Running {
            get {
                return ResourceManager.GetString("StatusMessage.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存中.
        /// </summary>
        internal static string StatusMessage_Saving {
            get {
                return ResourceManager.GetString("StatusMessage.Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録されていないプレイヤーQRコードです.
        /// </summary>
        internal static string StatusMessage_UnregisteredPlayerQR {
            get {
                return ResourceManager.GetString("StatusMessage.UnregisteredPlayerQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 記録完了.
        /// </summary>
        internal static string StatusMessage_WaitingPlayback {
            get {
                return ResourceManager.GetString("StatusMessage.WaitingPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタート待ち.
        /// </summary>
        internal static string StatusMessage_WaitingRun {
            get {
                return ResourceManager.GetString("StatusMessage.WaitingRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理者画面.
        /// </summary>
        internal static string tabPage_Admin_Text {
            get {
                return ResourceManager.GetString("tabPage_Admin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メイン画面.
        /// </summary>
        internal static string tabPage_Main_Text {
            get {
                return ResourceManager.GetString("tabPage_Main.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初期化画面.
        /// </summary>
        internal static string tabPage_System_Text {
            get {
                return ResourceManager.GetString("tabPage_System.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6台のクライアントとサーバーを起動しおえたら「システムの初期化」ボタンを押してください。
        ///初期化すると、待ち時間（アイドル時）の音楽とアナウンスの声が先頭から流れ始めます。
        ///      .
        /// </summary>
        internal static string textBox1_Text {
            get {
                return ResourceManager.GetString("textBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「システムの初期化」のあと、3分程度たってから「床情報の初期化」を行います。
        ///このとき、走る場所（スクリーンの前）に
        ///誰もいないことを確認してください。
        ///床情報を初期化している間は、画面が黒くなります。
        ///      .
        /// </summary>
        internal static string textBox2_Text {
            get {
                return ResourceManager.GetString("textBox2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2つの初期化が終わったら、
        ///このボタンでメイン画面に
        ///移りましょう。.
        /// </summary>
        internal static string textBox3_Text {
            get {
                return ResourceManager.GetString("textBox3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string toolStripStatusLabel1_Text {
            get {
                return ResourceManager.GetString("toolStripStatusLabel1.Text", resourceCulture);
            }
        }
    }
}
